/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/D602FMDiEYj
 */

export function CodeCom({code}) {
  return (
    <div className="relative p-4 bg-[#2d2d2d] rounded-md text-sm text-white font-mono">
      <pre className="overflow-x-auto">
        <code>
          {`${code}`}
        </code>
      </pre>
      
    </div>
  );
}
